config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get "/home", to: "static_pages#home"

  get "/help", to: "static_pages#help"

  get "/about", to: "static_pages#about"

  get "/contact", to: "static_pages#contact"

  get "/signup", to: "users#new"

  post "/signup", to: "users#create"

  get "/lang", to: "application#change_language"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  resources :account_activations, only: %i(edit)
  resources :microposts, only: %i(create destroy)
  resources :password_resets, only: %i(new create edit update)
  resources :relationships, only: %i(create destroy)
  resources :users do
    member do
      get :following, :followers
    end
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :find_user, :valid_user, :check_expiration, only: %i(edit update)

  def new; end

  def create
    user = User.find_by email: params[:password_reset][:email].downcase
    if user
      send_mail_valid_user user
    else
      flash.now[:danger] = t "password_resets.controller.flash.not_found_email"
      render :new
    end
  end

  def edit; end

  def update
    if params[:user][:password].empty?
      user.errors.add password: t("password_resets.controller.error.pass_empty")
      render_edit
    elsif user.update_attributes user_params
      after_update_pass user
    else
      render_edit
    end
  end

  private

  attr_reader :user

  def after_update_pass user
    log_in user
    flash[:success] = t "password_resets.controller.flash.has_reset_pass"
    redirect_to user
  end

  def check_expiration
    return unless user.password_reset_expired?
    flash[:danger] = t "password_resets.controller.flash.pass_reset_expired"
    redirect_to new_password_reset_url
  end

  def render_edit
    render :edit
  end

  def redirect_root
    redirect_to root_url
  end

  def find_user
    return if (@user = User.find_by email: params[:email])
    flash[:danger] = t "password_resets.controller.flash.not_found_email"
    redirect_root
  end

  def send_mail_valid_user user
    reset_token = User.new_token
    user.create_reset_digest reset_token
    UserMailer.password_reset(user, reset_token).deliver_now
    flash[:info] = t "password_resets.controller.flash.intruction"
    redirect_to root_url
  end

  def user_params
    params.require(:user).permit :password, :password_confirmation
  end

  def valid_user
    action_not_activate user unless user && user.activated?
    return if user.authenticated? :reset, params[:id]
    flash[:danger] = t "password_resets.controller.flash.not_authenticated"
    redirect_root
  end

  def action_not_activate user
    flash[:danger] = t "password_resets.controller.flash.not_activated"
    user.send_activation_email
    redirect_root
  end
end

app/views/password_resets/edit.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".h1" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: password_reset_path(params[:id]) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password, t(".password") %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, t(".confirmation") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t(".button_submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".h1" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :password_reset, url: password_resets_path do |f| %>
      <%= f.label :email, t(".label_mail") %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.submit t(".submit") , class: "btn btn-primary" %>
    <% end %>
  </div>
</div>