config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get "/home", to: "static_pages#home"

  get "/help", to: "static_pages#help"

  get "/about", to: "static_pages#about"

  get "/contact", to: "static_pages#contact"

  get "/signup", to: "users#new"

  post "/signup", to: "users#create"

  get "/lang", to: "application#change_language"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  resources :account_activations, only: %i(edit)
  resources :microposts, only: %i(create destroy)
  resources :password_resets, only: %i(new create edit update)
  resources :relationships, only: %i(create destroy)
  resources :users do
    member do
      get :following, :followers
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="error-explanation">
    <div class="alert alert-danger">
      <%= t ".h1" %>
      <%= pluralize object.errors.count, t(".error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if feed_items.any? %>
  <ol class="microposts">
    <%= render feed_items %>
  </ol>
  <%= will_paginate feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for micropost do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: t(".placeholder_text_area") %>
  </div>
  <%= f.submit t(".submit"), class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
  </span>
<% end %>

app/views/shared/_stats.html.erb
<% user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path user %>">
    <strong id="following" class="stat">
      <%= user.following.count %>
    </strong>
    <%= t ".following" %>
  </a>
  <a href="<%= followers_user_path user %>">
    <strong id="followers" class="stat">
      <%= user.followers.count %>
    </strong>
    <%= t ".followers" %>
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size:
  Settings.views.shared.user_info.gravatar_size), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t(".link_my_profile"), current_user %></span>
<span><%= pluralize current_user.microposts.count, t(".micropost") %></span>