config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get "/home", to: "static_pages#home"

  get "/help", to: "static_pages#help"

  get "/about", to: "static_pages#about"

  get "/contact", to: "static_pages#contact"

  get "/signup", to: "users#new"

  post "/signup", to: "users#create"

  get "/lang", to: "application#change_language"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  resources :account_activations, only: %i(edit)
  resources :microposts, only: %i(create destroy)
  resources :password_resets, only: %i(new create edit update)
  resources :relationships, only: %i(create destroy)
  resources :users do
    member do
      get :following, :followers
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".p1" %>
    <%= link_to t(".link_rails"), "http://www.railstutorial.org/" %>
    <%= t ".p2" %>
    <%= link_to t(".link_michael"), "http://www.michaelhartl.com/" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".link_bout"), about_path %></li>
      <li><%= link_to t(".link_contact"), contact_path %></li>
      <li><%= link_to t(".link_new"), "http://news.railstutorial.org/" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".link_app"), root_path, class: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".link_home"), root_path %></li>
        <li><%= link_to t(".link_help"), help_path %></li>
        <li><%= link_to t("lang.eng"), lang_path(lang: :en) %></li>
        <li><%= link_to t("lang.viet"), lang_path(lang: :vi) %></li>
        <% if logged_in? %>
          <li><%= link_to t(".link_user"), users_path %></li>
          <li class="dropdown">
            <%= link_to("#", class: "dropdown-toggle",
              data: {toggle: "dropdown"}) do %>
                <%= t(".p_account") %>
                <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".link_profile"), current_user %></li>
              <li><%= link_to t(".link_setting"),
                edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".link_log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".link_log_in"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"%>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
    <%= javascript_include_tag "i18n" %>
    <%= javascript_include_tag "translations", skip_pipeline: true %>
    <script type="text/javascript">
      I18n.defaultLocale = "<%= I18n.default_locale %>";
      I18n.locale = "<%= I18n.locale %>";
    </script>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>